{
 "title": "Model Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "continuous",
    "query": {
     "query": "metrics(feature_([0-9].*)_value_bucket)"
    }
   },
   {
    "name": "discrete",
    "query": {
     "query": "metrics(feature_([0-9].*)_value_total)"
    }
   },
   {
    "name": "interval",
    "query": "2m, 5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "duration", "query": "2m" }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "KL Divergence (30m)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n(sum(inference_value_baseline_total) by (bin) + 1) / ignoring (bin) group_left() (sum(inference_value_baseline_total) + count(sum(inference_value_baseline_total) by (bin))) * ln(\n((sum(inference_value_baseline_total) by (bin) + 1) / ignoring (bin) group_left() (sum(inference_value_baseline_total) + count(sum(inference_value_baseline_total) by (bin)))) / \n((sum(increase(inference_value_total[30m])) by (bin) + 1) / ignoring (bin) group_left() (sum(increase(inference_value_total[30m])) + count(sum(inference_value_total) by (bin))))\n)) + sum(\n(sum(increase(inference_value_total[30m])) by (bin) + 1) / ignoring (bin) group_left() (sum(increase(inference_value_total[30m])) + count(sum(inference_value_total) by (bin))) * ln(\n((sum(increase(inference_value_total[30m])) by (bin) + 1) / ignoring (bin) group_left() (sum(increase(inference_value_total[30m])) + count(sum(inference_value_total) by (bin)))) /\n((sum(inference_value_baseline_total) by (bin) + 1) / ignoring (bin) group_left() (sum(inference_value_baseline_total) + count(sum(inference_value_baseline_total) by (bin))))\n))"
    }
   ]
  },
  {
   "title": "K-S Test (30m)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1, abs(\nsum(inference_value_baseline_bucket) by (le) / ignoring(le) group_left max(sum(inference_value_baseline_bucket) by (le)) -\nsum(increase(inference_value_bucket[30m])) by (le) / ignoring(le) group_left max(sum(increase(inference_value_bucket[30m])) by (le))\n))",
     "legendFormat": "yhat={{le}}"
    }
   ]
  },
  { "title": "$discrete", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "discrete" },
  {
   "title": "Baseline distribution over training set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum([[discrete]]_baseline_total) by (bin)",
     "legendFormat": "{{ bin }}"
    }
   ]
  },
  {
   "title": "Feature value distribution over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase([[discrete]]_total[$duration])) by (bin)",
     "legendFormat": "{{ bin }}"
    }
   ]
  },
  {
   "title": "KL Divergence over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n(sum([[discrete]]_baseline_total) by (bin) + 1) / ignoring (bin) group_left() (sum([[discrete]]_baseline_total) + count(sum([[discrete]]_baseline_total) by (bin))) * ln(\n((sum([[discrete]]_baseline_total) by (bin) + 1) / ignoring (bin) group_left() (sum([[discrete]]_baseline_total) + count(sum([[discrete]]_baseline_total) by (bin)))) / \n((sum(increase([[discrete]]_total[$duration])) by (bin) + 1) / ignoring (bin) group_left() (sum(increase([[discrete]]_total[$duration])) + count(sum([[discrete]]_total) by (bin))))\n)) + sum(\n(sum(increase([[discrete]]_total[$duration])) by (bin) + 1) / ignoring (bin) group_left() (sum(increase([[discrete]]_total[$duration])) + count(sum([[discrete]]_total) by (bin))) * ln(\n((sum(increase([[discrete]]_total[$duration])) by (bin) + 1) / ignoring (bin) group_left() (sum(increase([[discrete]]_total[$duration])) + count(sum([[discrete]]_total) by (bin)))) /\n((sum([[discrete]]_baseline_total) by (bin) + 1) / ignoring (bin) group_left() (sum([[discrete]]_baseline_total) + count(sum([[discrete]]_baseline_total) by (bin))))\n))"
    }
   ]
  },
  { "title": "$continuous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "continuous" },
  {
   "title": "Baseline distribution over training set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum([[continuous]]_baseline_bucket) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Feature value distribution over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase([[continuous]]_bucket[$duration])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "K-S Test over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1, abs(\nsum([[continuous]]_baseline_bucket) by (le) / ignoring(le) group_left max(sum([[continuous]]_baseline_bucket) by (le)) -\nsum(increase([[continuous]]_bucket[$duration])) by (le) / ignoring(le) group_left max(sum(increase([[continuous]]_bucket[$duration])) by (le))\n))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "Regression", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Baseline distribution over test set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(inference_value_baseline_bucket) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Inference value distribution over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(inference_value_bucket[$duration])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "K-S Test over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1, abs(\nsum(inference_value_baseline_bucket) by (le) / ignoring(le) group_left max(sum(inference_value_baseline_bucket) by (le)) -\nsum(increase(inference_value_bucket[$duration])) by (le) / ignoring(le) group_left max(sum(increase(inference_value_bucket[$duration])) by (le))\n))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Classification",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Baseline distribution over test set",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(inference_value_baseline_total) by (bin)",
       "legendFormat": "{{ bin }}"
      }
     ]
    },
    {
     "title": "Inference value distribution over $duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(inference_value_total[$duration])) by (bin)",
       "legendFormat": "{{ bin }}"
      }
     ]
    },
    {
     "title": "KL Divergence over $duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(\n(sum(inference_value_baseline_total) by (bin) + 1) / ignoring (bin) group_left() (sum(inference_value_baseline_total) + count(sum(inference_value_baseline_total) by (bin))) * ln(\n((sum(inference_value_baseline_total) by (bin) + 1) / ignoring (bin) group_left() (sum(inference_value_baseline_total) + count(sum(inference_value_baseline_total) by (bin)))) / \n((sum(increase(inference_value_total[$duration])) by (bin) + 1) / ignoring (bin) group_left() (sum(increase(inference_value_total[$duration])) + count(sum(inference_value_total) by (bin))))\n)) + sum(\n(sum(increase(inference_value_total[$duration])) by (bin) + 1) / ignoring (bin) group_left() (sum(increase(inference_value_total[$duration])) + count(sum(inference_value_total) by (bin))) * ln(\n((sum(increase(inference_value_total[$duration])) by (bin) + 1) / ignoring (bin) group_left() (sum(increase(inference_value_total[$duration])) + count(sum(inference_value_total) by (bin)))) /\n((sum(inference_value_baseline_total) by (bin) + 1) / ignoring (bin) group_left() (sum(inference_value_baseline_total) + count(sum(inference_value_baseline_total) by (bin))))\n))"
      }
     ]
    }
   ]
  },
  {
   "title": "Ground truth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average inference value per $interval window",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(inference_value_sum[$interval])) / sum(increase(inference_value_count[$interval]))",
       "legendFormat": "Probability"
      }
     ]
    }
   ]
  }
 ]
}