groups:
  - name: alert_rules
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance [{{ $labels.instance }}] down"
          description: "[{{ $labels.instance }}] of job [{{ $labels.job }}] has been down for more 1 minute"

      - alert: DatabaseDrift
        expr: evidently:data_drift:dataset_drift == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Dataset drifting from (instance {{ $labels.instance }})"
          description: "Dataset used by job [{{ $labels.job }}] drifted"

      - alert: FeaturesDrift
        expr: evidently:data_drift:n_drifted_features > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Features drifting from (instance {{ $labels.instance }})"
          description: "The number of feature drifted is {{ $value }}"
      
      - alert: TargetDrift
        expr: evidently:cat_target_drift:drift > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Target drifting from (instance {{ $labels.instance }})"
          description: "Target by job [{{ $labels.job }}] drifted"

      - alert: HighCPUseconds
        expr: process_cpu_seconds_total{job="service"} > 80
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Host high CPU load (instance {{ $labels.instance }})"
          description: "CPU load is > 80 seconds total\n  VALUE = {{ $value }}  of job [{{ $labels.job }}]\n LABELS: {{ $labels }}"